# Generated by Django 4.0.4 on 2022-05-15 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_addcity2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='user',
        ),
        migrations.DeleteModel(
            name='AddCity',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
